version: '3'

tasks:
  default:
    desc: Runs the dev task.
    cmds:
      - task: dev

  dev:
    desc: Runs Hugo in development mode.
    cmds:
      - hugo server -D

  build:
    desc: Builds the site for production.
    cmds:
      - hugo